version: '3.1'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Aman*2002
      MYSQL_DATABASE: tasksdb
      MYSQL_USER: hunterhhh412
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_HOST=db
  #     - DATABASE_USER=hunterhhh412
  #     - DATABASE_PASSWORD=123456
  #     - DATABASE_NAME=tasksdb
  #     - DATABASE_PORT=3306

volumes:
  db_data: