CREATE DATABASE IF NOT EXISTS tasksdb;
CREATE USER IF NOT EXISTS 'hunterhhh412'@'localhost' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON tasksdb.* TO 'hunterhhh412'@'localhost';
FLUSH PRIVILEGES;
USE tasksdb;
CREATE TABLE IF NOT EXISTS tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    completed BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);